apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application-automation.fullname" . }}
  labels:
    {{- include "application-automation.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  APP_BASE_URL: {{ .Values.config.appBaseUrl | quote }}
  PORT: {{ .Values.service.targetPort | quote }}
